### ISSUE TITLE
Dialogue File Format

### ISSUE THREAD

**Issue by gaycodegal** [gaycodegal/operator-12#17]
We need some standardized way of writing dialogue that allows us to call lua functions in response to clicking on options, link multiple dialogue sequences together so that we can graph-complex dialogue, and be able to load only the dialogue we need. 

Probably this should be loaded as a Lua file format that returns a table, but how exactly is undecided yet.

It would be nice if this could be parsed from a simpler file format.

Originally I was thinking Twined might be a good starting point for reference.

**Comment by stephoro** [comment]
Currently the lua-side data format is a table where it's keys are `entry points` which is to say you index into the table to get dialogue events.
{cats={...}, dogs={...}, ...}

A dialogue event should have the format
{text=DIALOGUE, options={repeated {fun=FUNCTION,text=BUTTON_LABEL}...}}

**Comment by gaycodegal** [comment]
done for now (it works, may need to revise)
